### ISSUE TITLE
Add create-amagaki-app

### ISSUE THREAD

**Issue by stevenle** [blinkk/amagaki#129]
Most modern web development tools initialize a project with a command like `npx create-react-app <projectid>`. Examples include, React/Preact, Next.js, Gatsby.

![Screen Shot 2021-12-17 at 7 01 56 AM](https://user-images.githubusercontent.com/387282/146564506-5bffe97e-6654-4395-b4bd-d1536994472f.jpg)

Amagaki should have an equivalent `npx create-amagaki-app <projectid>` which clones the starter. The "getting started" documentation above should reflect this, and there should also be a button that says something along the lines of "or check out an example" which points to the amagaki starter repo.

**Comment by jeremydw** [comment]
I've added and published a tool called `create-amagaki`. (`-app` isn't quite right since we are focused on websites at the moment). Plus, I discovered that Gatsby has moved to `create-gatsby` as well: https://www.npmjs.com/package/create-gatsby

Create Amagaki uses this lovely `ncc` tool from Vercel which makes the distributed package dependency-free (it basically concatenates and rewrites all JS dependencies into a single file): https://github.com/blinkk/amagaki/blob/main/packages/create-amagaki/package.json#L23

This has the side effect of making `npx create-amagaki` start up in just a second or two. We may want to use this same method for other oft-run CLI programs invoked via `npx` like `npx fileset upload`.

https://github.com/vercel/ncc

Create Amagaki currently just supports GitHub URLs and the default branch "main" but this could be changed in the future.

Usage:

```
npx create-amagaki
```
